spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tech_challenge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: tech-challenge-backend

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
