spring:
  datasource:
    url: jdbc:postgresql://db:5432/tech_challenge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
